### ISSUE TITLE
OBS Browser - Hardware acceleration nvidia working

### ISSUE THREAD

**Issue by JonBoyleCoding** [materusPL/Nixerus#9]
I noticed your comment here:

https://github.com/materusPL/Nixerus/blob/90839912fe9caea93ce0b2802a5b6cd65d337a8d/pkgs/apps/obs/default.nix#L172-L172

I can tell you that whatever changes you've made here for the hardware acceleration also works on my nvidia gpus!

**Comment by materusPL** [comment]
libcef provides ANGLE lib but it's not used in nixpkgs, kinda surprising it works for some people with native opengl libs.
There are changes in draft pull request so it will probably work on obs from nixpkgs when it'll get updated to 30.0.*
